spring:
  datasource:
    url: '{cipher}AYATHGKGbGd6uk5Ab86Sa7MgOb3F2uKohfdKE027OcAyq3rq79jwfK/hUAU9PsB9Vr0AF62s4hlr0IGYcsmgRHvDvg2/h22S9W7U2dL2sS3cShLY6kXIqqwTor0ncUQ5/Gp3ao+QYoL3QwFYY60KVw6EJmLzDTap8WRWvkbB6RJqIK7YHEP6oBNiWeoR8xXaYObQa6EiPZCNcvirH0izumfC1wjxHy2Z7HK5dbyAPBIvczYBqoxH0SvG27SqR+/XHJBJdiLY7EuRaEjhZAm49IRb2VKu+7PK8DmcdgeXSvFl5J09xKp8HtiRVXyJ0Y8012uYp8x2lISj6sFgGM4jIRY2oRDwsho54jkp55lJwfARdj64OGzD864g6TWOfW37Frg0qRyqUL0dShaU4vJrOVOCnVrBedLl1WVLSKfl0qRQMG0i4MKU73268Tbzqg5WS+VacTyciondhSlBDXgzR8anUFXIYrl03Gecgb2XPcWesCpznUVH+eWR2y7ktn5G/VAGVcD1mE4XAE4ergBn0S+ge+I/5q4JBKfAJp4c/xRgKY7m7EOqDcItL5p4Nuxso4w='
    driver-class-name: org.h2.Driver
    username: '{cipher}AYA3wUwQFuuiWxkEp0bp2mgEBFLvazdpeaN5LnQDJNUDL5U5+BAtQbgHf0yz6NbV/p121BvS5X2p1ZPyPUGf8XOmL7w5apBiohGoKKiSAhJ5RSnjaF6KJYYVPoKaYCW4MAeZ+sWSJPo+Lb8WrHtcQKvT5JZYRKTjMbgtjoSv/bKTGmGahlN7ARW+sYTgaaBVLrcFZ6EmNnIVuImk03fFEHozr8fOY1PTH/UALZ2+lHkNokF5EGe2tFIt1In4E+rzqK2S9Z7ErW6g3utAFT4T2TTq2DJmSy9uNZhPLHZtwrCIyKBzUvz7XiYtPH5fbp843MU31hevma2GIWHg+/kfhbY630KRxjzfG02FXB2Qm0qL6RyLXd0s4IJ079NdlvPr098RbvNTFahamO5xSV79JadQup5t2N9vgrhcduOFZ8WGiVOk5fXT0o+ef7tTvginTHzxBE8bMIsNLLt3nxSEv9P4zq+E0MCvseaqQC9CMEdX6KXXp8FQ2iNbK9fqPReFw4q8xNzuLTu/p2T+bnIFvHXxO6mPSkdy0vuPPrS6IQsMPg=='
    password:

jwt:
  expiration_time: 864000 
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK=

test:
  message: user-service

order_service:
  url: http://ORDER-SERVICE/order-service/v1/order/%s
